package de.shecken.grillshow.shared

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB4A8)
val md_theme_dark_onPrimary = Color(0xFF690100)
val md_theme_dark_primaryContainer = Color(0xFF930100)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_secondary = Color(0xFFFFB4A8)
val md_theme_dark_onSecondary = Color(0xFF690100)
val md_theme_dark_secondaryContainer = Color(0xFF930100)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_tertiary = Color(0xFFFFB4A8)
val md_theme_dark_onTertiary = Color(0xFF690100)
val md_theme_dark_tertiaryContainer = Color(0xFF930100)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFFFFFFF)
val md_theme_dark_inversePrimary = Color(0xFFC00100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A8)
val md_theme_dark_outlineVariant = Color(0xFF534341)
val md_theme_dark_scrim = Color(0xFF000000)
