name: Build & Test

on:
  push:
    branches:
    - feature/**
    - bugfix/**
    - release/**
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Read Secret and Write to Properties File
      run: |
        echo "youtube-data-api-key=\"${{ secrets.YOUTUBE_DATA_API_KEY }}\"" > local.properties
        cat local.properties
    - name: Verify Properties File
      run: |
        if ! grep -q 'youtube-data-api-key' local.properties ; then
            echo "ERROR: 'youtube-data-api-key' not found in local.properties"
            exit 1
        fi
        echo "Properties file successfully verified."
          # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew assemble

