name: Android CI

on:
  push:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Read Secret and Write to Properties File
      run: |
        echo "YOUTUBE_DATA_API_KEY=${{ secrets.YOUTUBE_DATA_API_KEY }}" > local.properties
        cat local.properties
    - name: Verify Properties File
      run: |
        if ! grep -q 'YOUTUBE_DATA_API_KEY' local.properties ; then
            echo "ERROR: 'YOUTUBE_DATA_API_KEY' not found in local.properties"
            exit 1
        fi
        echo "Properties file successfully verified."
    - name: Build with Gradle
      run: ./gradlew assemble

